export const APP_INIT = "APP_INIT";

export const NOTIFICATION_INFO = "NOTIFICATION_INFO";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FINISH = "SIGNUP_FINISH";

export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_FINISH = "SIGNIN_FINISH";

export const SIGNOUT_START = "SIGNOUT_START";
export const SIGNOUT_FINISH = "SIGNOUT_FINISH";

export const ROOMS_GET_START = "ROOMS_GET_START";
export const ROOMS_GET_FINISH = "ROOMS_GET_FINISH";

export const ROOM_JOIN_START = "ROOM_JOIN_START";
export const ROOM_JOIN_FINISH = "ROOM_JOIN_FINISH";

export const MESSAGE_SEND = "MESSAGE_SEND";
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE";

export const ACTION_SEND = "ACTION_SEND";
export const ACTION_RECEIVE = "ACTION_RECEIVE";