export const NOTIFICATION_INFO = "NOTIFICATION_INFO";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

export const JOIN_START = "JOIN_START";
export const JOIN_FINISH = "JOIN_FINISH";

export const READY_START = "READY_START";
export const READY_FINISH = "READY_FINISH";

export const MESSAGE_SEND = "MESSAGE_SEND";
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE";

export const ACTION_SEND = "ACTION_SEND";
export const ACTION_RECEIVE = "ACTION_RECEIVE";