export const NOTIFICATION_LOG = "NOTIFICATION_LOG";
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";
export const NOTIFICATION_WARNING = "NOTIFICATION_WARNING";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

export const JOIN_START = "JOIN_START";
export const JOIN_FINISH = "JOIN_FINISH";

export const LEAVE_START = "LEAVE_START";
export const LEAVE_FINISH = "LEAVE_FINISH";

export const GET_STATE_START = "GET_STATE_START";
export const GET_STATE_FINISH = "GET_STATE_FINISH";